org.gradle.jvmargs=-Xmx1G
org.gradle.configuration-cache=false
org.gradle.parallel=true
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.154.2+26.2
fabric_kotlin_version=1.13.12+kotlin.2.4.0
mod_version=1.0.0-alpha.1
maven_group=net.mrwooly357.prism
kotlinx_collections_immutable_version=0.5.0
